// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NordeaBank.Api.Data;

#nullable disable

namespace NordeaBank.Api.Migrations
{
    [DbContext(typeof(NordeaBankDbContext))]
    partial class NordeaBankDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NordeaBank.Api.Entities.Title", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Affected_From")
                        .HasColumnType("datetime2");

                    b.Property<int>("Worker_Ref_Id")
                        .HasColumnType("int");

                    b.Property<string>("Worker_Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Titles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Affected_From = new DateTime(2016, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Worker_Ref_Id = 1,
                            Worker_Title = "Manager"
                        },
                        new
                        {
                            Id = 2,
                            Affected_From = new DateTime(2016, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Worker_Ref_Id = 2,
                            Worker_Title = "Executive"
                        },
                        new
                        {
                            Id = 3,
                            Affected_From = new DateTime(2016, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Worker_Ref_Id = 8,
                            Worker_Title = "Executive"
                        },
                        new
                        {
                            Id = 4,
                            Affected_From = new DateTime(2016, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Worker_Ref_Id = 5,
                            Worker_Title = "Manager"
                        },
                        new
                        {
                            Id = 5,
                            Affected_From = new DateTime(2016, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Worker_Ref_Id = 4,
                            Worker_Title = "Asst. Manager"
                        },
                        new
                        {
                            Id = 6,
                            Affected_From = new DateTime(2016, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Worker_Ref_Id = 7,
                            Worker_Title = "Executive"
                        },
                        new
                        {
                            Id = 7,
                            Affected_From = new DateTime(2016, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Worker_Ref_Id = 6,
                            Worker_Title = "Lead"
                        },
                        new
                        {
                            Id = 8,
                            Affected_From = new DateTime(2016, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Worker_Ref_Id = 3,
                            Worker_Title = "Lead"
                        });
                });

            modelBuilder.Entity("NordeaBank.Api.Entities.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Joining_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Last_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "HR",
                            First_Name = "Monika",
                            Joining_Date = new DateTime(2014, 2, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Last_Name = "Arora",
                            Salary = 10000m
                        },
                        new
                        {
                            Id = 2,
                            Department = "Admin",
                            First_Name = "Niharika",
                            Joining_Date = new DateTime(2014, 6, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Last_Name = "Verma",
                            Salary = 80000m
                        },
                        new
                        {
                            Id = 3,
                            Department = "HR",
                            First_Name = "Vishal",
                            Joining_Date = new DateTime(2014, 2, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Last_Name = "Singhal",
                            Salary = 300000m
                        },
                        new
                        {
                            Id = 4,
                            Department = "Admin",
                            First_Name = "Amitabh",
                            Joining_Date = new DateTime(2014, 2, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Last_Name = "Singh",
                            Salary = 500000m
                        },
                        new
                        {
                            Id = 5,
                            Department = "Admin",
                            First_Name = "Vivek",
                            Joining_Date = new DateTime(2014, 6, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Last_Name = "Bhati",
                            Salary = 500000m
                        },
                        new
                        {
                            Id = 6,
                            Department = "Account",
                            First_Name = "Vipul",
                            Joining_Date = new DateTime(2014, 6, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Last_Name = "Diwan",
                            Salary = 200000m
                        },
                        new
                        {
                            Id = 7,
                            Department = "Account",
                            First_Name = "Satish",
                            Joining_Date = new DateTime(2014, 1, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Last_Name = "Kumar",
                            Salary = 7500m
                        },
                        new
                        {
                            Id = 8,
                            Department = "Admin",
                            First_Name = "Geetika",
                            Joining_Date = new DateTime(2014, 4, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Last_Name = "Chauhan",
                            Salary = 90000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
